server:
  port: 8081
  max-http-header-size: 102400
  servlet:
    context-path: /api

spring:
  profiles:
    active: default
  flyway:
    locations: classpath:db
  jpa:
    open-in-view: true
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flyway_spring_boot?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: password
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
      maximumPoolSize: 200
      minimumIdle: 10
      validationTimeout: 2500
      max-lifetime: 600000
      idle-timeout: 200000
